# Generated by Django 2.2.3 on 2019-07-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=150)),
                ('employees', models.CharField(max_length=200)),
            ],
        ),
    ]
