# Generated by Django 2.2.3 on 2019-07-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_auto_20190724_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Business.Business'),
        ),
    ]
