# Generated by Django 2.2.3 on 2019-07-31 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_auto_20190724_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_of_company', to='Business.Business'),
        ),
        migrations.CreateModel(
            name='BusinessEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='Business.Business')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Business.Employee')),
            ],
        ),
    ]
