# Generated by Django 2.2.3 on 2019-07-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_auto_20190731_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessemployee',
            old_name='business',
            new_name='business_of_employee',
        ),
        migrations.RenameField(
            model_name='businessemployee',
            old_name='employee',
            new_name='employee_of_business',
        ),
    ]
