# Generated by Django 2.2.3 on 2019-07-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_auto_20190731_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='business',
        ),
        migrations.AlterField(
            model_name='businessemployee',
            name='business_of_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_of_employee', to='Business.Business'),
        ),
        migrations.AlterField(
            model_name='businessemployee',
            name='employee_of_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_of_business', to='Business.Employee'),
        ),
    ]
